// Import language
import { getDictionary } from "../i18n/dictionary";

import type { Metadata } from "next";
import "./globals.css";

// import components
import { Navbar } from "./components/Navbar";
import { ThemeToggle } from "./components/ThemeToggle";
import { StarBackground } from "./components/StarBackground";
import { Footer } from "./components/Footer";

// SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: "en" | "es" }
}>) {
  const lang = (await params).lang;
  const t = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body>
        <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
          {/* Theme Toggle */}
          <ThemeToggle />
          {/* Background Effects */}
          <StarBackground />

          {/* Navbar */}
          <Navbar t={t.navbar} />
          
          <main>
            {/* Main Content */}
            {children}
          </main>

      {/* Footer */}
      <Footer t={t.footer} />
    </div>
      </body>
    </html>
  );
}
